In [47]:
import pandas as pd
import seaborn as sns
import numpy as np
import plotly.express as px

In [48]:
df = pd.read_csv("AEP_hourly.csv")

In [49]:
df.head()

              Datetime   AEP_MW
0  2004-12-31 01:00:00  13478.0
1  2004-12-31 02:00:00  12865.0
2  2004-12-31 03:00:00  12577.0
3  2004-12-31 04:00:00  12517.0
4  2004-12-31 05:00:00  12670.0

In [50]:
df.shape

(121273, 2)

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 121273 entries, 0 to 121272
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   Datetime  121273 non-null  str
 1   AEP_MW    121273 non-null  float64
dtypes: float64(1), str(1)
memory usage: 4.0 MB

In [52]:
df.isna().sum()

Datetime    0
AEP_MW      0
dtype: int64

In [53]:
df.describe()

              AEP_MW
count  121273.000000
mean    15499.513717
std      2591.399065
min      9581.000000
25%     13630.000000
50%     15310.000000
75%     17200.000000
max     25695.000000

In [54]:
df['Datetime'] = pd.to_datetime(df['Datetime'])

In [55]:
df.head()

             Datetime   AEP_MW
0 2004-12-31 01:00:00  13478.0
1 2004-12-31 02:00:00  12865.0
2 2004-12-31 03:00:00  12577.0
3 2004-12-31 04:00:00  12517.0
4 2004-12-31 05:00:00  12670.0

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 121273 entries, 0 to 121272
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   Datetime  121273 non-null  datetime64[us]
 1   AEP_MW    121273 non-null  float64
dtypes: datetime64[us](1), float64(1)
memory usage: 1.9 MB

In [57]:
df.sort_values("Datetime",inplace = True)

In [58]:
df.duplicated().sum()

np.int64(0)

In [59]:
df.duplicated("Datetime").sum()

np.int64(4)

In [60]:
df.drop_duplicates("Datetime",inplace = True)

In [61]:
df.duplicated("Datetime").sum()

np.int64(0)

In [62]:
full_range = pd.date_range(start=df['Datetime'].min(), end=df['Datetime'].max(), freq='h')
missing = full_range.difference(df['Datetime'])
print(len(missing))

27

In [63]:
df.set_index("Datetime",inplace = True)

In [64]:
df = df.resample('h').mean()

In [65]:
df = df.interpolate()

In [66]:
df.index

DatetimeIndex(['2004-10-01 01:00:00', '2004-10-01 02:00:00',
               '2004-10-01 03:00:00', '2004-10-01 04:00:00',
               '2004-10-01 05:00:00', '2004-10-01 06:00:00',
               '2004-10-01 07:00:00', '2004-10-01 08:00:00',
               '2004-10-01 09:00:00', '2004-10-01 10:00:00',
               ...
               '2018-08-02 15:00:00', '2018-08-02 16:00:00',
               '2018-08-02 17:00:00', '2018-08-02 18:00:00',
               '2018-08-02 19:00:00', '2018-08-02 20:00:00',
               '2018-08-02 21:00:00', '2018-08-02 22:00:00',
               '2018-08-02 23:00:00', '2018-08-03 00:00:00'],
              dtype='datetime64[us]', name='Datetime', length=121296, freq='h')

In [67]:
df.shape

(121296, 1)

In [68]:
Yearly = df.resample('YE').mean()
px.line(Yearly, y='AEP_MW', title = 'Yearly Average Enerfy Consumption')

In [69]:
monthly = df.resample('ME').mean()
px.line(monthly,y='AEP_MW', title='Montly Average Energy Consumption')

In [70]:
df['hour'] = df.index.hour
hourly = df.groupby('hour')['AEP_MW'].mean()
px.bar(hourly, title='Average Consumption by Hour of Day')

In [71]:
df['hour'] = df.index.hour
df['dayofweak'] = df.index.dayofweek
df['month'] = df.index.month
df['year'] = df.index.year
df['quarter'] = df.index.quarter

In [72]:
df['dayofyear'] = df.index.dayofyear
df['weekofyear'] = df.index.isocalendar().week.astype(int)
df['lag_1'] = df['AEP_MW'].shift(1)
df['lag_24'] = df['AEP_MW'].shift(24)
df['lag_168'] = df['AEP_MW'].shift(168)
df = df.dropna()

In [73]:
df

,AEP_MW,hour,dayofweak,month,year,quarter,dayofyear,weekofyear,lag_1,lag_24,lag_168
Datetime,,,,,,,,,,,
2004-10-08 01:00:00,12468.0,1,4,10,2004,4,282,41,13271.0,12484.0,12379.0
2004-10-08 02:00:00,12046.0,2,4,10,2004,4,282,41,12468.0,12054.0,11935.0
2004-10-08 03:00:00,11749.0,3,4,10,2004,4,282,41,12046.0,11745.0,11692.0
2004-10-08 04:00:00,11784.0,4,4,10,2004,4,282,41,11749.0,11757.0,11597.0
2004-10-08 05:00:00,11919.0,5,4,10,2004,4,282,41,11784.0,12041.0,11681.0
...,...,...,...,...,...,...,...,...,...,...,...
2018-08-02 20:00:00,17673.0,20,3,8,2018,3,214,31,18118.0,16579.0,19006.0
2018-08-02 21:00:00,17303.0,21,3,8,2018,3,214,31,17673.0,16457.0,18322.0
2018-08-02 22:00:00,17001.0,22,3,8,2018,3,214,31,17303.0,16197.0,17804.0
2018-08-02 23:00:00,15964.0,23,3,8,2018,3,214,31,17001.0,15259.0,16530.0
2018-08-03 00:00:00,14809.0,0,4,8,2018,3,215,31,15964.0,14125.0,15127.0

In [74]:
df.head()

,AEP_MW,hour,dayofweak,month,year,quarter,dayofyear,weekofyear,lag_1,lag_24,lag_168
Datetime,,,,,,,,,,,
2004-10-08 01:00:00,12468.0,1,4,10,2004,4,282,41,13271.0,12484.0,12379.0
2004-10-08 02:00:00,12046.0,2,4,10,2004,4,282,41,12468.0,12054.0,11935.0
2004-10-08 03:00:00,11749.0,3,4,10,2004,4,282,41,12046.0,11745.0,11692.0
2004-10-08 04:00:00,11784.0,4,4,10,2004,4,282,41,11749.0,11757.0,11597.0
2004-10-08 05:00:00,11919.0,5,4,10,2004,4,282,41,11784.0,12041.0,11681.0

In [75]:
from sklearn.model_selection import train_test_split

In [77]:
x= df[['hour', 'dayofweak', 'month', 'year', 'quarter', 'dayofyear', 'weekofyear', 'lag_1', 'lag_24', 'lag_168']]
y = df['AEP_MW']

xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,shuffle=False,)

In [ ]:
# %pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\thaku\appdata\local\programs\python\python312\lib\site-packages (from xgboost) (2.4.4)
Requirement already satisfied: scipy in c:\users\thaku\appdata\local\programs\python\python312\lib\site-packages (from xgboost) (1.17.1)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB 660.6 kB/s eta 0:02:34
   ---------------------------------------- 0.3/101.7 MB 2.6 MB/s eta 0:00:39
   ---------------------------------------- 0.4/101.7 MB 2.9 MB/s eta 0:00:35
   ---------------------------------------- 0.7/101.7 MB 3.5 MB/s eta 0:00:29
   ---------------------------------------- 1.0/101.7 MB 4.6 MB/s eta 0:00:22
    --------------------------------------- 1.4/101.7 MB 5.2 MB/s eta 0:00:20
    --------------------------------------- 1.9/101.7 MB 6.0 MB/s eta 0:00:17
    --------------------------------------- 2.3/101.7 MB 6.4 MB/s eta 0:00:16
   - -------------------------------------- 2.8/101.7 MB 6.9 MB/s eta 0:00:15
   - -------------------------------------- 3.2/101.7 MB 7.0 MB/s eta 0:00:15
   - -------------------------------------- 3.5/101.7 MB 7.0 MB/s eta 0:00:15
   - -------------------------------------- 3.7/101.7 MB 6.8 MB/s eta 0:00:15
   - -------------------------------------- 4.0/101.7 MB 7.0 MB/s eta 0:00:15
   - -------------------------------------- 4.4/101.7 MB 7.1 MB/s eta 0:00:14
   - -------------------------------------- 4.6/101.7 MB 6.9 MB/s eta 0:00:14
   - -------------------------------------- 5.0/101.7 MB 7.3 MB/s eta 0:00:14
   -- ------------------------------------- 5.3/101.7 MB 7.3 MB/s eta 0:00:14
   -- ------------------------------------- 5.8/101.7 MB 7.4 MB/s eta 0:00:13
   -- ------------------------------------- 6.2/101.7 MB 7.5 MB/s eta 0:00:13
   -- ------------------------------------- 6.6/101.7 MB 7.6 MB/s eta 0:00:13
   -- ------------------------------------- 7.1/101.7 MB 7.8 MB/s eta 0:00:13
   -- ------------------------------------- 7.2/101.7 MB 7.7 MB/s eta 0:00:13
   --- ------------------------------------ 7.8/101.7 MB 7.8 MB/s eta 0:00:12
   --- ------------------------------------ 8.2/101.7 MB 7.8 MB/s eta 0:00:12
   --- ------------------------------------ 8.7/101.7 MB 8.1 MB/s eta 0:00:12
   --- ------------------------------------ 9.1/101.7 MB 8.0 MB/s eta 0:00:12
   --- ------------------------------------ 9.6/101.7 MB 8.2 MB/s eta 0:00:12
   --- ------------------------------------ 10.0/101.7 MB 8.2 MB/s eta 0:00:12
   ---- ----------------------------------- 10.2/101.7 MB 8.1 MB/s eta 0:00:12
   ---- ----------------------------------- 10.6/101.7 MB 8.7 MB/s eta 0:00:11
   ---- ----------------------------------- 11.1/101.7 MB 9.0 MB/s eta 0:00:11
   ---- ----------------------------------- 11.6/101.7 MB 9.1 MB/s eta 0:00:10
   ---- ----------------------------------- 12.0/101.7 MB 9.1 MB/s eta 0:00:10
   ---- ----------------------------------- 12.3/101.7 MB 9.1 MB/s eta 0:00:10
   ----- ---------------------------------- 12.8/101.7 MB 9.1 MB/s eta 0:00:10
   ----- ---------------------------------- 13.3/101.7 MB 9.2 MB/s eta 0:00:10
   ----- ---------------------------------- 13.7/101.7 MB 9.4 MB/s eta 0:00:10
   ----- ---------------------------------- 14.1/101.7 MB 9.5 MB/s eta 0:00:10
   ----- ---------------------------------- 14.5/101.7 MB 9.5 MB/s eta 0:00:10
   ----- ---------------------------------- 15.1/101.7 MB 9.8 MB/s eta 0:00:09
   ------ --------------------------------- 15.6/101.7 MB 9.8 MB/s eta 0:00:09
   ------ --------------------------------- 16.1/101.7 MB 9.9 MB/s eta 0:00:09
   ------ --------------------------------- 16.5/101.7 MB 9.9 MB/s eta 0:00:09
   ------ --------------------------------- 17.0/101.7 MB 9.9 MB/s eta 0:00:09
   ------ --------------------------------- 17.3/101.7 MB 9.8 MB/s eta 0:00:09
   ------- -------------------------------- 17.8/101.7 MB 9.9 MB/s eta 0:00:09
   ------- -------------------------------- 18.1/101.7 MB 9.8 MB/s eta 0:00:09
   ------- -------------------------------- 18.6/101.7 MB 9.9 MB/s eta 0:00:09
   ------- -------------------------------- 19.1/101.7 MB 10.1 MB/s eta 0:00:09
   ------- -------------------------------- 19.1/101.7 MB 10.1 MB/s eta 0:00:09
   ------- -------------------------------- 19.8/101.7 MB 9.9 MB/s eta 0:00:09
   ------- -------------------------------- 20.2/101.7 MB 9.9 MB/s eta 0:00:09
   -------- ------------------------------- 20.7/101.7 MB 10.1 MB/s eta 0:00:09
   -------- ------------------------------- 21.2/101.7 MB 10.2 MB/s eta 0:00:08
   -------- ------------------------------- 21.6/101.7 MB 10.2 MB/s eta 0:00:08
   -------- ------------------------------- 22.2/101.7 MB 10.2 MB/s eta 0:00:08
   -------- ------------------------------- 22.6/101.7 MB 10.2 MB/s eta 0:00:08
   --------- ------------------------------ 23.1/101.7 MB 10.4 MB/s eta 0:00:08
   --------- ------------------------------ 23.4/101.7 MB 10.4 MB/s eta 0:00:08
   --------- ------------------------------ 23.8/101.7 MB 10.4 MB/s eta 0:00:08
   --------- ------------------------------ 24.5/101.7 MB 10.4 MB/s eta 0:00:08
   --------- ------------------------------ 25.0/101.7 MB 10.4 MB/s eta 0:00:08
   --------- ------------------------------ 25.4/101.7 MB 10.6 MB/s eta 0:00:08
   ---------- ----------------------------- 25.9/101.7 MB 10.6 MB/s eta 0:00:08
   ---------- ----------------------------- 26.4/101.7 MB 10.6 MB/s eta 0:00:08
   ---------- ----------------------------- 27.0/101.7 MB 10.6 MB/s eta 0:00:08
   ---------- ----------------------------- 27.4/101.7 MB 10.7 MB/s eta 0:00:07
   ----------- ---------------------------- 28.0/101.7 MB 10.7 MB/s eta 0:00:07
   ----------- ---------------------------- 28.4/101.7 MB 10.7 MB/s eta 0:00:07
   ----------- ---------------------------- 29.0/101.7 MB 10.7 MB/s eta 0:00:07
   ----------- ---------------------------- 29.5/101.7 MB 11.5 MB/s eta 0:00:07
   ----------- ---------------------------- 29.9/101.7 MB 11.1 MB/s eta 0:00:07
   ----------- ---------------------------- 30.5/101.7 MB 11.1 MB/s eta 0:00:07
   ------------ --------------------------- 31.0/101.7 MB 11.3 MB/s eta 0:00:07
   ------------ --------------------------- 31.5/101.7 MB 11.1 MB/s eta 0:00:07
   ------------ --------------------------- 32.0/101.7 MB 11.1 MB/s eta 0:00:07
   ------------ --------------------------- 32.7/101.7 MB 11.3 MB/s eta 0:00:07
   ------------ --------------------------- 32.9/101.7 MB 10.9 MB/s eta 0:00:07
   ------------- -------------------------- 33.4/101.7 MB 10.9 MB/s eta 0:00:07
   ------------- -------------------------- 34.0/101.7 MB 11.3 MB/s eta 0:00:06
   ------------- -------------------------- 34.5/101.7 MB 11.1 MB/s eta 0:00:07
   ------------- -------------------------- 35.0/101.7 MB 11.1 MB/s eta 0:00:07
   ------------- -------------------------- 35.3/101.7 MB 11.1 MB/s eta 0:00:06
   ------------- -------------------------- 35.5/101.7 MB 10.9 MB/s eta 0:00:07
   -------------- ------------------------- 35.9/101.7 MB 10.7 MB/s eta 0:00:07
   -------------- ------------------------- 36.6/101.7 MB 10.7 MB/s eta 0:00:07
   -------------- ------------------------- 36.9/101.7 MB 10.6 MB/s eta 0:00:07
   -------------- ------------------------- 37.4/101.7 MB 10.6 MB/s eta 0:00:07
   -------------- ------------------------- 37.9/101.7 MB 10.6 MB/s eta 0:00:07
   --------------- ------------------------ 38.5/101.7 MB 10.4 MB/s eta 0:00:07
   --------------- ------------------------ 39.1/101.7 MB 10.7 MB/s eta 0:00:06
   --------------- ------------------------ 39.5/101.7 MB 10.4 MB/s eta 0:00:06
   --------------- ------------------------ 40.0/101.7 MB 10.7 MB/s eta 0:00:06
   --------------- ------------------------ 40.4/101.7 MB 10.6 MB/s eta 0:00:06
   ---------------- ----------------------- 40.9/101.7 MB 10.7 MB/s eta 0:00:06
   ---------------- ----------------------- 41.4/101.7 MB 10.6 MB/s eta 0:00:06
   ---------------- ----------------------- 41.8/101.7 MB 10.6 MB/s eta 0:00:06
   ---------------- ----------------------- 42.4/101.7 MB 10.7 MB/s eta 0:00:06
   ---------------- ----------------------- 42.8/101.7 MB 10.6 MB/s eta 0:00:06
   ----------------- ---------------------- 43.4/101.7 MB 10.7 MB/s eta 0:00:06
   ----------------- ---------------------- 43.7/101.7 MB 10.7 MB/s eta 0:00:06
   ----------------- ---------------------- 44.2/101.7 MB 10.6 MB/s eta 0:00:06
   ----------------- ---------------------- 44.7/101.7 MB 10.7 MB/s eta 0:00:06
   ----------------- ---------------------- 45.1/101.7 MB 10.4 MB/s eta 0:00:06
   ----------------- ---------------------- 45.7/101.7 MB 11.1 MB/s eta 0:00:06
   ------------------ --------------------- 46.0/101.7 MB 10.9 MB/s eta 0:00:06
   ------------------ --------------------- 46.5/101.7 MB 11.1 MB/s eta 0:00:05
   ------------------ --------------------- 46.9/101.7 MB 11.1 MB/s eta 0:00:05
   ------------------ --------------------- 47.3/101.7 MB 11.1 MB/s eta 0:00:05
   ------------------ --------------------- 47.9/101.7 MB 11.3 MB/s eta 0:00:05
   ------------------- -------------------- 48.4/101.7 MB 11.1 MB/s eta 0:00:05
   ------------------- -------------------- 49.0/101.7 MB 11.1 MB/s eta 0:00:05
   ------------------- -------------------- 49.4/101.7 MB 10.9 MB/s eta 0:00:05
   ------------------- -------------------- 49.8/101.7 MB 11.1 MB/s eta 0:00:05
   ------------------- -------------------- 50.3/101.7 MB 10.9 MB/s eta 0:00:05
   ------------------- -------------------- 50.6/101.7 MB 10.9 MB/s eta 0:00:05
   -------------------- ------------------- 51.2/101.7 MB 10.9 MB/s eta 0:00:05
   -------------------- ------------------- 51.5/101.7 MB 10.7 MB/s eta 0:00:05
   -------------------- ------------------- 52.0/101.7 MB 10.7 MB/s eta 0:00:05
   -------------------- ------------------- 52.5/101.7 MB 10.7 MB/s eta 0:00:05
   -------------------- ------------------- 53.0/101.7 MB 10.7 MB/s eta 0:00:05
   --------------------- ------------------ 53.5/101.7 MB 10.6 MB/s eta 0:00:05
   --------------------- ------------------ 53.9/101.7 MB 10.6 MB/s eta 0:00:05
   --------------------- ------------------ 54.4/101.7 MB 10.6 MB/s eta 0:00:05
   --------------------- ------------------ 54.8/101.7 MB 10.4 MB/s eta 0:00:05
   --------------------- ------------------ 55.4/101.7 MB 10.6 MB/s eta 0:00:05
   --------------------- ------------------ 55.7/101.7 MB 10.6 MB/s eta 0:00:05
   ---------------------- ----------------- 56.3/101.7 MB 10.6 MB/s eta 0:00:05
   ---------------------- ----------------- 56.8/101.7 MB 10.6 MB/s eta 0:00:05
   ---------------------- ----------------- 57.2/101.7 MB 10.4 MB/s eta 0:00:05
   ---------------------- ----------------- 57.7/101.7 MB 10.6 MB/s eta 0:00:05
   ---------------------- ----------------- 58.2/101.7 MB 10.4 MB/s eta 0:00:05
   ----------------------- ---------------- 58.8/101.7 MB 10.6 MB/s eta 0:00:05
   ----------------------- ---------------- 59.2/101.7 MB 10.4 MB/s eta 0:00:05
   ----------------------- ---------------- 59.9/101.7 MB 10.7 MB/s eta 0:00:04
   ----------------------- ---------------- 60.2/101.7 MB 10.4 MB/s eta 0:00:04
   ----------------------- ---------------- 60.8/101.7 MB 10.6 MB/s eta 0:00:04
   ------------------------ --------------- 61.3/101.7 MB 10.6 MB/s eta 0:00:04
   ------------------------ --------------- 61.7/101.7 MB 10.6 MB/s eta 0:00:04
   ------------------------ --------------- 62.3/101.7 MB 10.6 MB/s eta 0:00:04
   ------------------------ --------------- 62.8/101.7 MB 10.6 MB/s eta 0:00:04
   ------------------------ --------------- 63.3/101.7 MB 10.7 MB/s eta 0:00:04
   ------------------------ --------------- 63.5/101.7 MB 10.6 MB/s eta 0:00:04
   ------------------------- -------------- 64.1/101.7 MB 10.7 MB/s eta 0:00:04
   ------------------------- -------------- 64.5/101.7 MB 10.6 MB/s eta 0:00:04
   ------------------------- -------------- 65.0/101.7 MB 10.9 MB/s eta 0:00:04
   ------------------------- -------------- 65.3/101.7 MB 10.7 MB/s eta 0:00:04
   ------------------------- -------------- 65.8/101.7 MB 10.6 MB/s eta 0:00:04
   -------------------------- ------------- 66.4/101.7 MB 10.7 MB/s eta 0:00:04
   -------------------------- ------------- 66.8/101.7 MB 10.6 MB/s eta 0:00:04
   -------------------------- ------------- 67.3/101.7 MB 10.9 MB/s eta 0:00:04
   -------------------------- ------------- 67.7/101.7 MB 10.7 MB/s eta 0:00:04
   -------------------------- ------------- 68.1/101.7 MB 10.7 MB/s eta 0:00:04
   --------------------------- ------------ 68.6/101.7 MB 10.6 MB/s eta 0:00:04
   --------------------------- ------------ 69.0/101.7 MB 10.4 MB/s eta 0:00:04
   --------------------------- ------------ 69.6/101.7 MB 10.6 MB/s eta 0:00:04
   --------------------------- ------------ 70.1/101.7 MB 10.4 MB/s eta 0:00:04
   --------------------------- ------------ 70.7/101.7 MB 10.7 MB/s eta 0:00:03
   ---------------------------- ----------- 71.2/101.7 MB 10.6 MB/s eta 0:00:03
   ---------------------------- ----------- 71.7/101.7 MB 10.7 MB/s eta 0:00:03
   ---------------------------- ----------- 72.1/101.7 MB 10.6 MB/s eta 0:00:03
   ---------------------------- ----------- 72.7/101.7 MB 10.7 MB/s eta 0:00:03
   ---------------------------- ----------- 73.1/101.7 MB 10.7 MB/s eta 0:00:03
   ---------------------------- ----------- 73.6/101.7 MB 10.4 MB/s eta 0:00:03
   ----------------------------- ---------- 74.0/101.7 MB 10.7 MB/s eta 0:00:03
   ----------------------------- ---------- 74.5/101.7 MB 10.6 MB/s eta 0:00:03
   ----------------------------- ---------- 75.0/101.7 MB 10.7 MB/s eta 0:00:03
   ----------------------------- ---------- 75.4/101.7 MB 10.4 MB/s eta 0:00:03
   ----------------------------- ---------- 76.0/101.7 MB 10.7 MB/s eta 0:00:03
   ------------------------------ --------- 76.4/101.7 MB 10.7 MB/s eta 0:00:03
   ------------------------------ --------- 76.9/101.7 MB 10.6 MB/s eta 0:00:03
   ------------------------------ --------- 77.4/101.7 MB 10.6 MB/s eta 0:00:03
   ------------------------------ --------- 77.8/101.7 MB 10.6 MB/s eta 0:00:03
   ------------------------------ --------- 78.3/101.7 MB 10.7 MB/s eta 0:00:03
   ------------------------------ --------- 78.5/101.7 MB 10.4 MB/s eta 0:00:03
   ------------------------------- -------- 79.1/101.7 MB 10.7 MB/s eta 0:00:03
   ------------------------------- -------- 79.6/101.7 MB 10.7 MB/s eta 0:00:03
   ------------------------------- -------- 79.9/101.7 MB 10.6 MB/s eta 0:00:03
   ------------------------------- -------- 80.5/101.7 MB 10.7 MB/s eta 0:00:02
   ------------------------------- -------- 80.9/101.7 MB 10.6 MB/s eta 0:00:02
   -------------------------------- ------- 81.5/101.7 MB 10.9 MB/s eta 0:00:02
   -------------------------------- ------- 81.9/101.7 MB 10.7 MB/s eta 0:00:02
   -------------------------------- ------- 82.5/101.7 MB 10.7 MB/s eta 0:00:02
   -------------------------------- ------- 83.0/101.7 MB 10.9 MB/s eta 0:00:02
   -------------------------------- ------- 83.3/101.7 MB 10.6 MB/s eta 0:00:02
   -------------------------------- ------- 83.9/101.7 MB 10.7 MB/s eta 0:00:02
   --------------------------------- ------ 84.3/101.7 MB 10.6 MB/s eta 0:00:02
   --------------------------------- ------ 84.9/101.7 MB 10.7 MB/s eta 0:00:02
   --------------------------------- ------ 85.3/101.7 MB 10.7 MB/s eta 0:00:02
   --------------------------------- ------ 85.7/101.7 MB 10.7 MB/s eta 0:00:02
   --------------------------------- ------ 86.4/101.7 MB 10.9 MB/s eta 0:00:02
   ---------------------------------- ----- 86.7/101.7 MB 11.1 MB/s eta 0:00:02
   ---------------------------------- ----- 87.3/101.7 MB 11.1 MB/s eta 0:00:02
   ---------------------------------- ----- 87.6/101.7 MB 10.7 MB/s eta 0:00:02
   ---------------------------------- ----- 88.1/101.7 MB 11.1 MB/s eta 0:00:02
   ---------------------------------- ----- 88.6/101.7 MB 11.1 MB/s eta 0:00:02
   ----------------------------------- ---- 89.1/101.7 MB 11.1 MB/s eta 0:00:02
   ----------------------------------- ---- 89.6/101.7 MB 11.1 MB/s eta 0:00:02
   ----------------------------------- ---- 90.0/101.7 MB 11.1 MB/s eta 0:00:02
   ----------------------------------- ---- 90.6/101.7 MB 11.3 MB/s eta 0:00:01
   ----------------------------------- ---- 90.9/101.7 MB 10.9 MB/s eta 0:00:01
   ----------------------------------- ---- 91.5/101.7 MB 11.1 MB/s eta 0:00:01
   ------------------------------------ --- 92.0/101.7 MB 11.1 MB/s eta 0:00:01
   ------------------------------------ --- 92.3/101.7 MB 11.1 MB/s eta 0:00:01
   ------------------------------------ --- 92.9/101.7 MB 11.1 MB/s eta 0:00:01
   ------------------------------------ --- 93.2/101.7 MB 11.1 MB/s eta 0:00:01
   ------------------------------------ --- 93.7/101.7 MB 11.1 MB/s eta 0:00:01
   ------------------------------------- -- 94.4/101.7 MB 11.3 MB/s eta 0:00:01
   ------------------------------------- -- 94.8/101.7 MB 11.3 MB/s eta 0:00:01
   ------------------------------------- -- 95.3/101.7 MB 11.3 MB/s eta 0:00:01
   ------------------------------------- -- 95.4/101.7 MB 11.3 MB/s eta 0:00:01
   ------------------------------------- -- 96.1/101.7 MB 11.3 MB/s eta 0:00:01
   -------------------------------------- - 96.6/101.7 MB 11.3 MB/s eta 0:00:01
   -------------------------------------- - 97.1/101.7 MB 11.1 MB/s eta 0:00:01
   -------------------------------------- - 97.8/101.7 MB 11.3 MB/s eta 0:00:01
   -------------------------------------- - 98.2/101.7 MB 11.3 MB/s eta 0:00:01
   -------------------------------------- - 98.7/101.7 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------  99.2/101.7 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------  99.8/101.7 MB 11.3 MB/s eta 0:00:01
   --------------------------------------  100.3/101.7 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  100.8/101.7 MB 11.3 MB/s eta 0:00:01
   --------------------------------------  101.4/101.7 MB 11.7 MB/s eta 0:00:01
   --------------------------------------  101.7/101.7 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  101.7/101.7 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  101.7/101.7 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  101.7/101.7 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  101.7/101.7 MB 11.5 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 9.4 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [78]:
from xgboost import XGBRegressor
model = XGBRegressor()

In [79]:
model.fit(xtrain,ytrain)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [80]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

yPred = model.predict(xtest)

In [81]:
mae = mean_absolute_error(ytest,yPred)

In [82]:
rmse = np.sqrt(mean_squared_error(ytest,yPred))

In [83]:
print(f'MAE: {mae:.2f}')
print(f'RMSE: {rmse:.2f}')

MAE: 135.73
RMSE: 179.88

In [84]:
print(r2_score(ytest,yPred))

0.9945881620428292

In [85]:
print(r2_score(ytrain, model.predict(xtrain)))
print(r2_score(ytest, model.predict(xtest)))

0.996375085859545
0.9945881620428292

In [86]:
import joblib
joblib.dump(model,'engery_model.pkl')

['engery_model.pkl']